// Unexpire passwords for dev mode
zn "%SYS"
Do ##class(Security.Users).UnExpireUserPasswords("*")

// Load classes from durable source
zn "USER"
set importPath = "/opt/irisapp/src"
write "Loading classes at '", importPath, "' ...", !
set errors = ""
do $System.OBJ.Import(importPath,"cuk",,.errors)
if errors = 0 { write "Classes loaded successfully" } Else { write errors, " errors occurred while loading classes!", ! }
halt