ROUTINE PackageManager.PackageManager [Type=INC]

#define PackageManagerAPI			 "/csp/user/rest/packagemanager/"
#define PackageManagerRESTClass			 "PackageManager.API.REST"
#define tmpFilePath			 $system.Util.InstallDirectory()_"tmp\packagemanager\"
#define APIDIR             "DIR"
#define APIPKG            "PKG"
#define exportTaskFilePath			 $system.Util.InstallDirectory()_"tmp\packagemanager\task\export\"
#define ExportProjectTaskSectionTitle			 "Export Project Task"
#define ProjectContentViewerSectionTitle			 "Projects Content Viewer"
#define ExportedReleaseSectionTitle			 "Exported Release"
#define InstallationSectionTitle			 "Install Package Manager"
#define defaultTaskDescription			 "Export projects utility task"
