ROUTINE PackageManager.PackageManager [Type=INC]

#define ProjectName			 "IRIS Package Manager"
#define PackageManagerVersion			 "0.1.0"
#define PackageManagerAPI			 "/csp/user/rest/packagemanager/"
#define PackageManagerRESTClass			 "PackageManager.API.REST"
#define APIDIR             "DIR"
#define APIPKG            "PKG"
#define ExportProjectTaskSectionTitle			 "Export Project Task"
#define ProjectContentViewerSectionTitle			 "Projects Content Viewer"
#define ExportedReleaseSectionTitle			 "Exported Release"
#define InstallationSectionTitle			 "Install Package Manager"
#define defaultTaskDescription			 "Export projects utility task"
#define systemClassesToExclude			 "CSPX,Ens,EnsHL7,EnsLib,HS,HSMOD,HIPAA,%"